version: '3.8'
services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ott
    ports:
      - "3306:3306"
    volumes:
      - mysql_bookworm_data:/var/lib/mysql
      
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3002:3000"
    depends_on:
      - mysql
    volumes:
      - mysqlwb_data:/var/lib/mysqlwb
      - mysqlwb_config:/config
      - ./mysql-dumps:/config/dumps
volumes:
  mysql_bookworm_data:
  mysqlwb_config:
  mysqlwb_data:
